# Generated by Django 5.1.11 on 2025-08-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaisetting',
            name='api_key',
            field=models.CharField(default='', help_text='OpenAI API Key', max_length=255),
        ),
        migrations.AlterField(
            model_name='openaisetting',
            name='model_name',
            field=models.CharField(default='', help_text='OpenAI Model Name', max_length=100),
        ),
    ]
