# Generated by Django 5.1.11 on 2025-08-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_openaisetting_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreAPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='', help_text='Core API URL', max_length=255)),
                ('api_token', models.CharField(default='', help_text='Core API Token', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
