# Generated by Django 5.1.11 on 2025-08-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_coreapisetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreapisetting',
            options={'verbose_name': 'Core API Setting'},
        ),
    ]
