# Generated by Django 5.2.5 on 2025-08-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_coreapisetting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreapisetting',
            name='api_token',
            field=models.CharField(blank=True, default='', help_text='Core API Token', max_length=255),
        ),
        migrations.AlterField(
            model_name='coreapisetting',
            name='api_url',
            field=models.URLField(blank=True, default='', help_text='Core API URL', max_length=255),
        ),
    ]
