# Generated by Django 5.2.5 on 2025-08-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_coreapisetting_api_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaisetting',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='OpenAI API Key', max_length=255),
        ),
        migrations.AlterField(
            model_name='openaisetting',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text='OpenAI Model Name', max_length=100),
        ),
    ]
