# Generated by Django 5.2.5 on 2025-09-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_openaisetting_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseAdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_account_file', models.FileField(blank=True, help_text='Firebase Admin SDK Service Account JSON file', null=True, upload_to='firebase/')),
                ('project_id', models.CharField(blank=True, default='', help_text='Firebase Project ID (optional, usually in service account file)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firebase Admin Setting',
            },
        ),
    ]
