# Generated by Django 5.2.5 on 2025-09-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_firebaseadminsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseadminsetting',
            name='service_account_json',
            field=models.TextField(blank=True, default='', help_text='Firebase Admin SDK Service Account JSON content (alternative to file upload for production)'),
        ),
    ]
