# Generated by Django 5.2.5 on 2025-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Photo URL'),
        ),
    ]
