# Generated by Django 5.2.5 on 2025-09-04 09:34

import instagram.misc
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=instagram.misc.get_user_profile_picture_upload_location)),
                ('original_profile_picture_url', models.URLField(help_text='The original profile picture URL from Instagram', max_length=2500)),
                ('biography', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('allow_auto_update_stories', models.BooleanField(default=False)),
                ('allow_auto_update_profile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated From API')),
            ],
        ),
    ]
