# Generated by Django 5.2.5 on 2025-09-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='original_profile_picture_url',
            field=models.URLField(blank=True, help_text='The original profile picture URL from Instagram', max_length=2500),
        ),
    ]
