# Generated by Django 5.2.5 on 2025-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_user_original_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_api_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
