# Generated by Django 5.2.5 on 2025-09-07 04:32

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_user_raw_api_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('instagram_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('profile_picture', models.TextField(blank=True, max_length=100, null=True)),
                ('original_profile_picture_url', models.URLField(blank=True, help_text='The original profile picture URL from Instagram', max_length=2500)),
                ('biography', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('raw_api_data', models.JSONField(blank=True, null=True)),
                ('allow_auto_update_stories', models.BooleanField(default=False)),
                ('allow_auto_update_profile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('api_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated From API')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
