# Generated by Django 5.2.5 on 2025-09-07 05:15

import instagram.misc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_historicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='profile_picture',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=instagram.misc.get_user_profile_picture_upload_location),
        ),
    ]
