# Generated by Django 5.2.6 on 2025-09-09 03:25

import django.db.models.deletion
import instagram.misc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_historicaluser_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('thumbnail_url', models.URLField(max_length=2500)),
                ('media_url', models.URLField(blank=True, max_length=2500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=instagram.misc.get_user_story_upload_location)),
                ('media', models.FileField(blank=True, null=True, upload_to=instagram.misc.get_user_story_upload_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story_created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.user')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='UserUpdateStoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.user')),
            ],
            options={
                'verbose_name': 'User Update Story Log',
                'verbose_name_plural': 'User Update Story Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
