# Generated by Django 5.2.6 on 2025-09-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_story_userupdatestorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='raw_api_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
