# Generated by Django 5.2.6 on 2025-09-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_story_raw_api_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2500),
        ),
    ]
