# Generated by Django 5.2.5 on 2025-08-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('endpoint', models.CharField(max_length=200)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_logs_ap_created_d743de_idx'), models.Index(fields=['status'], name='api_logs_ap_status_7ebd00_idx'), models.Index(fields=['endpoint'], name='api_logs_ap_endpoin_622263_idx'), models.Index(fields=['response_status_code'], name='api_logs_ap_respons_afba59_idx')],
            },
        ),
    ]
