# Generated by Django 5.2.5 on 2025-08-29 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apirequestlog',
            name='api_logs_ap_endpoin_622263_idx',
        ),
        migrations.RemoveField(
            model_name='apirequestlog',
            name='endpoint',
        ),
    ]
